export default {
    FETCH_NEW_RELEASES_REQUEST: "FETCH_NEW_RELEASES_REQUEST",
    FETCH_NEW_RELEASES_SUCCESS: "FETCH_NEW_RELEASES_SUCCESS",
    FETCH_NEW_RELEASES_FAILED: "FETCH_NEW_RELEASES_FAILED",
};
