export default {
    AUTHORIZE_REQUEST: "AUTHORIZE_REQUEST",
    AUTHORIZE_SUCCESS: "AUTHORIZE_SUCCESS",
    AUTHORIZE_FAILED: "AUTHORIZE_FAILED",
    WRITE_ACCESS_TOKEN: "WRITE_ACCESS_TOKEN",
    CLEAR_ACCESS_TOKEN: "CLEAR_ACCESS_TOKEN",
};
