export default {
    FETCH_CATEGORY_PLAYLISTS_REQUEST: "FETCH_CATEGORY_PLAYLISTS_REQUEST",
    FETCH_CATEGORY_PLAYLISTS_SUCCESS: "FETCH_CATEGORY_PLAYLISTS_SUCCESS",
    FETCH_CATEGORY_PLAYLISTS_FAILED: "FETCH_CATEGORY_PLAYLISTS_FAILED",
};
