export default {
    FETCH_FEATURED_PLAYLISTS_REQUEST: "FETCH_FEATURED_PLAYLISTS_REQUEST",
    FETCH_FEATURED_PLAYLISTS_SUCCESS: "FETCH_FEATURED_PLAYLISTS_SUCCESS",
    FETCH_FEATURED_PLAYLISTS_FAILED: "FETCH_FEATURED_PLAYLISTS_FAILED",
};
