export default {
    FETCH_PLAYLIST_REQUEST: "FETCH_PLAYLIST_REQUEST",
    FETCH_PLAYLIST_SUCCESS: "FETCH_PLAYLIST_SUCCESS",
    FETCH_PLAYLIST_FAILED: "FETCH_PLAYLIST_FAILED",
    UPDATE_TRACK: "UPDATE_TRACK",
    GO_TO_TRACK: "GO_TO_TRACK",
};
